import type { Metadata } from 'next';
import { IBM_Plex_Mono, Fredericka_the_Great, Roboto } from 'next/font/google';
import './reset.css';
import './globals.scss';

// Context
import { ContextProvider } from './context/AppContext';

const ibmPlexMono = IBM_Plex_Mono({
	variable: '--font-ibm-plex-mono',
	weight: ['400', '500', '600', '700'],
	subsets: ['latin'],
});

const frederickaTheGreat = Fredericka_the_Great({
	variable: '--font-fredericka-the-great',
	weight: '400',
	subsets: ['latin'],
});

const roboto = Roboto({
	variable: '--font-roboto',
	weight: ['400', '500', '700'],
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${ibmPlexMono.variable} ${roboto.variable} ${frederickaTheGreat.variable}`}
			>
				<ContextProvider>{children}</ContextProvider>
			</body>
		</html>
	);
}
