import type { Metadata } from 'next';
import { Cascadia_Mono, Roboto, Fredericka_the_Great } from 'next/font/google';
import './reset.css';
import './globals.css';

const cascadiaMono = Cascadia_Mono({
	variable: '--font-cascadia-mono',
	weight: '400',
	subsets: ['latin'],
});

const frederickaTheGreat = Fredericka_the_Great({
	variable: '--font-fredericka-the-great',
	weight: '400',
	subsets: ['latin'],
});

const roboto = Roboto({
	variable: '--font-roboto',
	weight: ['400', '500', '700'],
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${cascadiaMono.variable} ${roboto.variable} ${frederickaTheGreat.variable}`}
			>
				{children}
			</body>
		</html>
	);
}
